# Site settings
author: Samantha Diaz
title: Flatiron School Diaries
header-img: img/home-bg.png
email: samidiaz3@gmail.com
copyright_name: Samantha Diaz
description: > # this means to ignore newlines until "baseurl:"
  My blog maintained while studying Software Engineering at Flatiron. 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ssdiaz

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
